name: Run Docker on Push

on:
  push:
    branches:
      -'**'
jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  

      - name: Build Docker image
        run: docker build -t tp1 .

      - name: Run Docker container
        run: docker run -v ${{ github.workspace }}:/app tp1
 
      - name: Commit and push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}

            git add .
            git commit -m "Add results from Docker run" || echo "No changes to commit"
            git push origin HEAD:${{ github.ref_name }}
